name: onedrive_netflix
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^5.6.0

  google_sign_in: ^6.2.2
  http: ^1.2.2
  firebase_auth: ^5.3.4
  shared_preferences: ^2.3.4
  go_router: ^14.6.2
  talker: ^4.5.2
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

    - .env

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/ProductSans-Medium.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
