name: "Build"

on:
  pull_request:
    branches:
      - dev
      - test
      - master
  push:
    branches:
      - dev
      - test
      - master

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.18.0
